# -*- coding: utf-8 -*-
"""csvCreation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15nxuGxQXdaYzDroxwxzcquWcORAHCeMT
"""

import pandas as pd
df = pd.read_csv('mix_40_features.csv')
df.head()

import pandas as pd

pair_df = pd.DataFrame()


for i in range(len(df)-1):
    # pick the two rows you want to combine
    row1 = df.iloc[i]
    row2 = df.iloc[i+1]

    # rename columns so nothing collides
    row1.index = [f"{c}_1" for c in df.columns]
    row2.index = [f"{c}_2" for c in df.columns]

    # combine side-by-side into one wide row
    wide_row = pd.concat([row1, row2])

    # convert to DataFrame (1 row)
    wide_row_df = wide_row.to_frame().T



    # append to original df
    pair_df = pd.concat([pair_df, wide_row_df], ignore_index=True)


pair_df.head()

pair_df.to_csv('songPairs.csv', index=False)