# -*- coding: utf-8 -*-
"""Model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1a_CIfHungk0elUWjieX_cCubwu4WSOqS

BeatNet Classifier

- Most code currently taken from lecture notes
"""

import torch
from matplotlib import pyplot as plt
import seaborn as sns
import pandas as pd

markers = ['o', 's']

def binary_cross_entropy(q, y):
    return -(y * torch.log(q) + (1 - y) * torch.log(1 - q)).mean()

def sigmoid(z):
    return 1 / (1 + torch.exp(-z))

class BinaryLogisticRegression:
    def __init__(self, n_features):
        self.w = torch.zeros(n_features, 1)

    def forward(self, X):
        return sigmoid(X @ self.w)

class GradientDescentOptimizer:
    def __init__(self, model, lr=0.1):
        self.model = model
        self.lr = lr

    def grad_func(self, X, y):
        q = self.model.forward(X)
        return 1/X.shape[0] * ((q - y).T @ X).T


    def step(self, X, y):
        grad = self.grad_func(X, y)
        with torch.no_grad():
            self.model.w -= self.lr * grad

import pandas as pd
url = "https://raw.githubusercontent.com/middcs/data-science-notes/refs/heads/main/data/australia-weather/weatherAUS.csv"

df = pd.read_csv(url)
df.head()
# df["Pressure9am"] = df["Pressure9am"]/1e3
# df["Humidity3pm"] = df["Humidity3pm"]/100

df.dropna(subset=['RainTomorrow', 'Humidity3pm', 'Pressure3pm'], inplace=True)

# CSV READING CODE (REPLACE ABOVE BLOCK LATER):
'''
df = pd.read_csv('songData.csv')
'''

X = df[['Humidity3pm', 'Pressure3pm']].to_numpy()
y = (df['RainTomorrow'] == 'Yes').to_numpy().astype(float).reshape(-1, 1)

train_frac = 0.8
n = X.shape[0]
n_train = int(train_frac * n)

X_train = X[:n_train, :]
y_train = y[:n_train, :]

X_test = X[n_train:, :]
y_test = y[n_train:, :]

"""Polynomial Feature Model:"""

def polynomial_features(X, degree):
    n_samples, n_features = X.shape
    features = [torch.ones(n_samples, 1)]  # start with the intercept term
    for d in range(1, degree + 1):
        for i in range(n_features):
            features.append(X[:, i:i+1] ** d)
    poly = torch.cat(features, dim=1)
    aug = torch.cat([torch.ones((poly.shape[0], 1)), poly], dim=1)
    # scale the features to prevent numerical instability
    aug = aug / torch.max(torch.abs(aug), dim=0).values

    return aug

X_train_poly = polynomial_features(torch.tensor(X_train, dtype=torch.float32), degree=5)

n_features = X_train_poly.shape[1]

y_train_tensor = torch.tensor(y_train, dtype=torch.float32)
model = BinaryLogisticRegression(n_features=n_features)
opt = GradientDescentOptimizer(model, lr=2)

losses = []
for epoch in range(10000):

    q = model.forward(X_train_poly)
    loss = binary_cross_entropy(q, y_train_tensor)

    losses.append(loss.item())
    opt.step(X_train_poly, y_train_tensor)


x1_grid = torch.linspace(X[:,0].min(), X[:,0].max(), 100)
x2_grid = torch.linspace(X[:,1].min(), X[:,1].max(), 100)
xx1, xx2 = torch.meshgrid(x1_grid, x2_grid, indexing='ij')

grid = torch.cat([xx1.reshape(-1, 1), xx2.reshape(-1, 1)], dim=1)
grid = polynomial_features(grid, degree=5)

with torch.no_grad():
    q_grid = model.forward(grid).reshape(xx1.shape)

fig, ax = plt.subplots(figsize=(6, 6))

ax.contour(xx1, xx2, q_grid, levels=[0.5], colors='k', linewidths=1, extent = (x1_grid.min(), x1_grid.max(), x2_grid.min(), x2_grid.max()), linestyles='--')
ax.contourf(xx1, xx2, q_grid, levels=torch.linspace(0, 1, steps=10), alpha=0.3, cmap='BrBG', extent = (x1_grid.min(), x1_grid.max(), x2_grid.min(), x2_grid.max()))


ax.set(title='Learned decision boundary', xlabel='Humidity3pm', ylabel='Pressure3pm')

for i, label in enumerate(["No rain tomorrow", "Rain tomorrow"]):
    idx = (y_test[:1000, 0] == i)
    ax.scatter(X_test[:1000, 0][idx], X_test[:1000, 1][idx], c = y_test[:1000, 0][idx], label=f'{label}', edgecolor='k', marker=markers[i],   cmap = 'BrBG', vmin = -0.5, vmax = 1.5, alpha = 0.7)

plt.legend()

"""Linear Feature Model (Ignore?):"""

n_features = X_train.shape[1] + 1  # +1 for intercept
X_train_aug = torch.ones((X_train.shape[0], n_features))
X_train_aug[:, 1:] = torch.tensor(X_train, dtype=torch.float32)

y_train_tensor = torch.tensor(y_train, dtype=torch.float32)
model = BinaryLogisticRegression(n_features=n_features)
opt = GradientDescentOptimizer(model, lr=0.00001)

losses = []
for epoch in range(20000):

    q = model.forward(X_train_aug)
    loss = binary_cross_entropy(q, y_train_tensor)

    losses.append(loss.item())
    opt.step(X_train_aug, y_train_tensor)

# VISUALIZATION ONE:

plt.plot(losses, color = "grey")
t = plt.title('Loss over training')
plt.xlabel('Epoch')
plt.ylabel('Binary cross-entropy loss')
plt.ylim(0, 1)
plt.semilogx()

# VIS TWO:
x1_grid = torch.linspace(X[:,0].min(), X[:,0].max(), 100)
x2_grid = torch.linspace(X[:,1].min(), X[:,1].max(), 100)
xx1, xx2 = torch.meshgrid(x1_grid, x2_grid, indexing='ij')
grid = torch.cat([torch.ones_like(xx1).reshape(-1, 1), xx1.reshape(-1, 1), xx2.reshape(-1, 1)], dim=1)
with torch.no_grad():
    q_grid = model.forward(grid).reshape(xx1.shape)

fig, ax = plt.subplots(figsize=(6, 6))

ax.contour(xx1, xx2, q_grid, levels=[0.5], colors='k', linewidths=1, extent = (x1_grid.min(), x1_grid.max(), x2_grid.min(), x2_grid.max()), linestyles='--')
ax.contourf(xx1, xx2, q_grid, levels=torch.linspace(0, 1, steps=10), alpha=0.3, cmap='BrBG', extent = (x1_grid.min(), x1_grid.max(), x2_grid.min(), x2_grid.max()))


ax.set(title='Learned decision boundary', xlabel='Humidity3pm', ylabel='Pressure3pm')

for i, label in enumerate(["No rain tomorrow", "Rain tomorrow"]):
    idx = (y_test[:1000, 0] == i)
    ax.scatter(X_test[:1000, 0][idx], X_test[:1000, 1][idx], c = y_test[:1000, 0][idx], label=f'{label}', edgecolor='k', marker=markers[i],   cmap = 'BrBG', vmin = -0.5, vmax = 1.5, alpha = 0.7)

plt.legend()

# obtain the probabilities q_test
X_test_aug = torch.ones((X_test.shape[0], n_features))
X_test_aug[:, 1:] = torch.tensor(X_test, dtype=torch.float32)
y_test_tensor = torch.tensor(y_test, dtype=torch.float32)
q_test = model.forward(X_test_aug)

# obtain class predictions via thresholding and compute accuracy
y_test_pred = (q_test >= 0.5).float()
accuracy_test = (y_test_pred == y_test_tensor).float().mean()
print(f'Test accuracy: {accuracy_test:.3f}')